version: '3'
services:
    schemefront:
        image: schemefront_img
        ports:
            - '8088:8088'
        environment:
            - NODE_ENV=docker
            - NODE_OPTIONS="--max-old-space-size=4096"
        links:
            - 'schemeapi'
            - 'modelsapi'
    modelsapi:
        image: modelsapi_img
        ports:
            - '8087:8087'
        environment:
            - NODE_ENV=docker
            - NODE_OPTIONS="--max-old-space-size=4096"
        links:
            - 'schemeapi:prestoapi'
            - 'schememodels:mysql'
    schemeapi:
        image: schemeapi_img
        ports:
            - '8086:8086'
        environment:
            - NODE_ENV=docker
            - NODE_OPTIONS="--max-old-space-size=4096"
    schememodels:
        image: mariadb
        environment:
            - MYSQL_DATABASE=schememodels
            - MYSQL_ROOT_PASSWORD=rootscheme
        volumes:

            - dbdata:/var/lib/mysql
        ports:
            - '8085:8085'
volumes:
    dbdata: